name: ci
on:
  pull_request:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v4
      - name: "setup python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'requirements-dev.txt'
      - name: "pip install"
        run: pip install -r requirements-dev.txt
      - name: "pytest"
        run: python -m pytest tests/**
